### ISSUE TITLE
Can we use goroutine

### ISSUE THREAD

**Issue by GRdaukiya** [paul-mannino/go-fuzzywuzzy#3]
When I have to find the best 50 with accepted match score 70, with 22k choices taking 2s,
It's too high
Using goroutines can we optimize it further or parallel computing?
Please suggest me possible solution.

**Comment by paul-mannino** [comment]
Code is about 10x faster after https://github.com/paul-mannino/go-fuzzywuzzy/issues/4

Let me know if this gets you closer to your performance goals.

If not, feel free to reopen and give a little more context as to how you're using this code. The code itself is pretty step-dependent, so opportunities for parallelism within the code are probably not great. With my limited knowledge of your usecase, I might also suggest wrapping your calls (or batches of calls) to the library code in go routines. It sounds like your consumption of the library would be much easier to parallelize.
